url: https://pmichael95.github.io/
baseurl: .

# Site settings
title: Philip Michael - Software Developer
email: phil-mik@hotmail.com
description: "Avid Programmer. Inspired Software Developer. Passionate Gamer and Game Developer. I am currently a Computer Science student in Canada, and always looking for new opportunities!"


# Build settings
markdown: kramdown
permalink: pretty